[package]
name = "mentat-ingest"
version = "0.0.1"
edition = "2021"

[dependencies]
walkdir = "2"
blake3 = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
globset = "0.4"
