[package]
name = "mentat-embedder"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1"
candle-core = "0.9"
candle-nn = "0.9"
candle-transformers = "0.9"
tokenizers = "0.20"
serde_json = "1"
once_cell = "1"
